#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor DP-2 -d I III V VII IX
#bspc monitor HDMI-0 -d II IV VI VIII X
bspc monitor DP-2 -d 1 3 5 7
bspc monitor HDMI-0 -d 2 4 6 8

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# configs
bspc config focus_follows_pointer true
bspc config top_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# rules

# initial startup config
picom --experimental-backend &
nitrogen --restore &
xset r rate 200 50 &
numlockx &
dunst &
udiskie -a &
unclutter &
playerctld &
