#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc rule -r *

#bspc monitor DP-2 -d I III V VII IX
#bspc monitor HDMI-0 -d II IV VI VIII X
bspc monitor DP-2 -d 1 3 5 7 9
bspc monitor HDMI-0 -d 2 4 6 8 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# configs
bspc config focus_follows_pointer true
bspc config top_padding 20

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='2'
bspc rule -a Spotify desktop='2'
bspc rule -a Steam desktop='2'
bspc rule -a Thunderbeard desktop='2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# rules
bspc rule -a scratchpad sticky=on state=floating hidden=on
[ "$(ps -x | grep -c 'scratchpadwin')" -eq "1" ] && $TERMINAL --class scratchpadwin -e ~/.scripts/scratchpad &

# initial startup config
killall -q picom; picom --experimental-backend &
nitrogen --restore &
xset r rate 200 50 &
killall -q numlockx; numlockx &
killall -q dunst; dunst &
killall -q udiskie; udiskie -a &
killall -q unclutter; unclutter &
killall -q playerctld; playerctld &
~/.scripts/launch_polybar.sh &

# apps
#killall -q discord; discord &
#killall -q thunderbird; thunderbird &
#killall -q steam; steam &
#killall -q spotify; spotify &

# TODO make general worksapce automatically tab
# TODO make all ufocused windows hidden when going into monacle or fullscreen
# TODO better scratchpad
